version: "3.9"

services:
  database:
    image: postgres:14
    container_name: minha_vacina_database
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres
  database_tests:
    image: postgres:14
    container_name: minha_vacina_database_test
    restart: always
    env_file:
      - .env.test
    ports:
      - 5433:5432


volumes:
  pgdata:
    driver: local
